insert ignore into `forum` (`name`, `spider`) values 
	('Alphabay', 'alphabay_forum'), 
	('Dream Market Forum', 'dreammarket_forum'),
	('Trade Route Forum', 'traderoute_forum'),
	('RsClub Market Forum', 'rsclub_forum'),
	('Darknet Heroes League', 'dhl_forum'),
	('Apple Market Forum', 'applemarket_forum'),
	('House Of Lions', 'houseoflions_forum'),
	('Aero Forum', 'aero_forum'),
	('Cannabis Growers & Merchants Coop Forum', 'cgmc_forum');

insert ignore into `user_propkey` (`name`, `prettyname`) values 
	('joined_on', 'Joined on'),
	('likes_received', 'Likes received'), 
	('last_activity', 'Last activity'), 
	('avatar', 'Avatar'), 
	('message_count', 'Message count'), 
	('user_id', 'User ID'), 
	('title', 'Title'), 
	('banner', 'Banner'),
	('location', 'Location'), 
	('website', 'Website'), 
	('signature', 'Signature'), 
	('post_count', 'Post Count'), 
	('last_post', 'Last post on'),
	('realname', 'Real name'),
	('jabber', 'Jabber'),
	('microsoft_account', 'Microsoft Account'),
	('icq', 'ICQ'), 
	('yahoo_messenger', 'Yahoo Messenger'),
	('membergroup', 'Member group'),
	('postgroup', 'Post group'),
	('reputation_power', 'Reputation power'),
	('rep_bars', 'Reputation'),
	('stars', 'Stars'),
	('karma', 'Karma'),
	('post_per_day', 'Post per days'),
	('age', 'Age'),
	('group', 'Group'),
	('last_active', 'Last active'),
	('gender', 'Gender'),
	('custom_title', 'Custom title'),
	('personal_text', 'Personal text'),
	('msn', 'MSN Messenger');