from twisted.internet import defer
from twisted.internet.error import TimeoutError, DNSLookupError, \
        ConnectionRefusedError, ConnectionDone, ConnectError, \
        ConnectionLost, TCPTimedOutError
from twisted.web.client import ResponseFailed
from scrapy import signals
from scrapy.exceptions import IgnoreRequest
from scrapy.utils.misc import load_object
import logging
import os
from IPython import embed
from scrapy.utils.request import request_fingerprint

# This middleware must be the first download middleware.
# When it sees a request generated by the replay_spider_middleware. It returns the response hidden in the meta attribute
# and stop further processing.
class ReplayRequestMiddleware(object):
	def __init__(self):
		self.logger = logging.getLogger('ReplayRequestMiddleware')

	def process_request(self, request, spider):
		if '__replay__response__' in request.meta:
			return request.meta['__replay__response__']	# Stop execution of request. Return response.