import scrapy


class Ads(scrapy.Item) :
	vendor_username = scrapy.Field()
	offer_id = scrapy.Field()
	title = scrapy.Field()
	price = scrapy.Field()
	price_options = scrapy.Field()
	ships_to = scrapy.Field()
	ships_to_except = scrapy.Field()	
	ships_from = scrapy.Field()
	escrow = scrapy.Field()	
	description = scrapy.Field()
	category = scrapy.Field()
	shipping_options = scrapy.Field()
	relativeurl = scrapy.Field()
	fullurl = scrapy.Field()
	ads_class = scrapy.Field()
	in_stock = scrapy.Field()
	stock = scrapy.Field()
	terms_and_conditions = scrapy.Field()
	multilisting = scrapy.Field()
	multisig = scrapy.Field()
	views = scrapy.Field()
	minimum_order = scrapy.Field()
	maximum_order = scrapy.Field()
	already_sold = scrapy.Field()
	country = scrapy.Field()
	replace_time = scrapy.Field()
	auto_accept = scrapy.Field()
	price_usd = scrapy.Field()
	price_ltc = scrapy.Field()
	price_bch = scrapy.Field()
	price_xmr = scrapy.Field()
	accepted_currencies = scrapy.Field()

class AdsImage(scrapy.Item):
	ads_id = scrapy.Field()
	image_urls = scrapy.Field()
	images = scrapy.Field()

class User(scrapy.Item) :
	username = scrapy.Field()
	successful_transactions = scrapy.Field()
	average_rating = scrapy.Field()
	agora_rating = scrapy.Field()
	nucleus_rating = scrapy.Field()	
	alphabay_rating = scrapy.Field()
	abraxas_rating = scrapy.Field()
	midlle_earth_rating = scrapy.Field()
	hansa_rating = scrapy.Field()
	dreammarket_rating = scrapy.Field()
	valhalla_rating = scrapy.Field()
	oasis_rating = scrapy.Field()
	trusted_seller = scrapy.Field()
	verified = scrapy.Field()
	fe_enabled = scrapy.Field()
	join_date = scrapy.Field()
	last_active = scrapy.Field()
	terms_and_conditions = scrapy.Field()
	public_pgp_key = scrapy.Field()
	relativeurl = scrapy.Field()
	fullurl = scrapy.Field()
	subscribers = scrapy.Field()
	positive_feedback =  scrapy.Field()
	neutral_feedback =  scrapy.Field()
	negative_feedback = scrapy.Field()
	level = scrapy.Field()
	avg_volume = scrapy.Field()
	profile = scrapy.Field()
	ship_from = scrapy.Field()
	ship_to = scrapy.Field()
	title = scrapy.Field()
	exp = scrapy.Field()
	successful_transactions_as_buyer = scrapy.Field()
	news = scrapy.Field()
	shipping_information = scrapy.Field()
	forum_posts = scrapy.Field()
	feedback_received = scrapy.Field()
	refund_policy = scrapy.Field()
	reship_policy = scrapy.Field()

class ProductRating(scrapy.Item):
	submitted_on = scrapy.Field()
	rating = scrapy.Field()
	comment = scrapy.Field()
	ads_id = scrapy.Field()
	submitted_by = scrapy.Field()
	delivery_time = scrapy.Field()

class UserRating(scrapy.Item):
	submitted_on = scrapy.Field()
	rating = scrapy.Field()
	comment = scrapy.Field()
	username = scrapy.Field()
	submitted_by = scrapy.Field()
	delivery_time = scrapy.Field()

	communication = scrapy.Field()
	speed = scrapy.Field()
	stealth = scrapy.Field()
	quality = scrapy.Field()
	payment_type = scrapy.Field()
	item_name = scrapy.Field()
	submitter_level = scrapy.Field()
	price = scrapy.Field()


